### ISSUE TITLE
ERC721

### ISSUE THREAD

**Issue by SquintyNB** [AlgoNetwork/Bee-Sender-v2#10]
Would you be able to implement ERC721 (NFTs) to be sent in bulk?
I'm guessing it would be:

Contract address:token
0xb650279e3d726B0c75C984cAA55341cB87A7F501:4497
0xb650279e3d726B0c75C984cAA55341cB87A7F501:5919

etc..

Thanks!

**Comment by AlgoNetwork** [comment]
Yes,maybe add this function in the future.
