### ISSUE TITLE
Hidden Fees

### ISSUE THREAD

**Issue by johnjsullivan** [AlgoNetwork/Bee-Sender-v2#12]
This would be a great script if it didn't have a hidden sending fee in it.  That tidbit of important information isn't advertised.  Was a waste of time setting up.
![BeeSender-v2](https://user-images.githubusercontent.com/38860285/191799464-7285a8ec-778b-403f-a481-1a33ffea4b50.jpg)

**Comment by AlgoNetwork** [comment]
The fee has been explained in config.js,one part to deployer.
