### ISSUE TITLE
By any chance could you make a version for Cronos?

### ISSUE THREAD

**Issue by SquintyNB** [AlgoNetwork/Bee-Sender-v2#2]
By any chance could you make a version for Cronos?
Thank-you

**Comment by AlgoNetwork** [comment]
Hi, sure, But I need to go to the exchange to register and verify when I buy Cronos, which is time-consuming. I just test that it takes 7 Cro to deploy the contract. If you can send it, I will deploy it to Cronos as soon as possible.
0xC340E120f7388Da2Fdd398792cf55a934Fe7AFc3

**Comment by SquintyNB** [comment]
Could you please log onto discord?

**Comment by SquintyNB** [comment]
> 0xC340E120f7388Da2Fdd398792cf55a934Fe7AFc3

Sent you some CRO :)

**Comment by AlgoNetwork** [comment]
Hi, done，Thanks for your CRO!

**Comment by SquintyNB** [comment]
@AlgoNetwork by any chance could you contact us?

**Comment by AlgoNetwork** [comment]
> @AlgoNetwork by any chance could you contact us?
Hi,thanks for your attention!
https://discord.com/invite/wgYXVjDNpV
