### ISSUE TITLE
Could your make a Cronos stake or claim script

### ISSUE THREAD

**Issue by SquintyNB** [AlgoNetwork/Bee-Sender-v2#4]
Anyway you can make a claim or stake script for cronos NFTs?

Thanks

**Comment by AlgoNetwork** [comment]
Stake NFT get ERC20 reward? 
Yes.

**Comment by SquintyNB** [comment]
> 

Yeah a reward from a pool.
It would require some editable math I'm guessing so everyone gets their fair share?

**Comment by AlgoNetwork** [comment]
1.User stake NFT to Smart contract.
2.When the user claims, the smart contract controls the token contract to mint the token to the user. Calculate the time for the user to stake NFT. The longer the user stakes, the more reward tokens they get.

**Comment by SquintyNB** [comment]
That sounds awesome, wish you were on discord more often!
