### ISSUE TITLE
Support for Candle (CNDL)

### ISSUE THREAD

**Issue by samisbakedham** [AlgoNetwork/Bee-Sender-v2#7]
[Website](https://candlelabs.org)
RPC URL: https://rpc.cndlchain.com
Chain ID: 534
Native currency: Candle (CNDL)
Sent 8,000 CNDL to cover any potential deployment costs to the address specified in the readme (0xc340e120f7388da2fdd398792cf55a934fe7afc3)  -[ here is the transaction link](https://candleexplorer.com/tx/0x5f8a46a8f1f29bf84353a41d9b08475b5fbfe45f66636196f7e407d86ea2afc0).
Thank you

**Comment by samisbakedham** [comment]
Really important!

**Comment by AlgoNetwork** [comment]
Done. ^ ^

**Comment by samisbakedham** [comment]
> Done. ^ ^

Thx fren.is it possible to add the ability to send the native coin / asset too? In this case - CNDL.
